export const vocabulary = {
  ru: {
    welcome: 'Добро пожаловать',
    signInText: 'Пожалуйста, войдите в систему',
    loginPlaceholder: 'ФИО',
    passwordPlaceholder: 'Пароль',
    loginButton: 'Войти',
    successMessage: 'Успешный вход!',
    errorMessage: 'Неверный логин или пароль',
    adminPanelTitle: 'Админ-панель',
    createUserTitle: 'Добавление пользователя',
    fullNameLabel: 'ФИО',
    emailLabel: 'Email',
    bankAccountLabel: 'Номер счёта',
    bankCardLabel: 'Номер банковской карты',
    documentUploadLabel: 'Документ',
    documentUploadHint: 'Загрузка пока отключена',
    createButton: 'Создать',
    searchUserTitle: 'Поиск пользователя',
    searchPrompt: 'Введите ФИО для поиска',
    searchPlaceholder: 'Например: Иванов Иван Иванович',
    searchButton: 'Найти',
    searchHint: 'Поиск осуществляется по полному совпадению части ФИО',
    userInfoTitle: 'Информация о пользователе',
    userNotSelected: 'Пользователь не выбран',
    noMatchesFound: 'Пользователи не найдены',
    selectUserPrompt: 'Выберите пользователя из списка',
    noData: 'Нет данных',
    logoutButton: 'Выйти',
    userCreatedMessage: 'Пользователь успешно создан',
    userFoundMessage: 'Пользователь найден',
    bankAccountRequired: 'Номер счёта обязателен для заполнения',
    bankAccountInvalid: 'Номер счёта должен содержать ровно 20 цифр',
    bankCardRequired: 'Номер карты обязателен для заполнения',
    bankCardInvalid: 'Номер карты должен содержать ровно 16 цифр',
    myGrants: 'Мои гранты',
    remainingAmount: 'Остаток',
    noGrants: 'У вас нет грантов',
    loadingGrants: 'Загрузка грантов...',
    scanQRCode: 'Сканировать QR-код',
    scanningQR: 'Сканирование...',
    qrScanSuccess: 'Операция одобрена',
    qrScanRejected: 'Операция отклонена',
    uploadReceipt: 'Загрузить чек',
    receiptUploaded: 'Чек успешно загружен',
    receiptUploadError: 'Ошибка загрузки чека',
    confirmOperation: 'Подтвердите операцию - загрузите чек',
    statusNotPurchased: 'Не проведена',
    statusProcessing: 'В обработке',
    statusCompleted: 'Готово',
    statusContractError: 'Свяжитесь с поддержкой',
    statusContractErrorAdmin: 'Свяжитесь с клиентом',
    items: 'Товары',
    noItems: 'Нет товаров',
    quantity: 'Количество',
    productName: 'Название товара',
    selectGrant: 'Выберите грант',
    selectCategory: 'Выберите категорию',
    passwordLabel: 'Пароль',
    passwordRequired: 'Пароль обязателен для заполнения',
    downloadReceipt: 'Скачать чек',
    contactClient: 'Свяжитесь с клиентом',
  },
  en: {
    welcome: 'Welcome back',
    signInText: 'Please sign in to continue',
    loginPlaceholder: 'Fullname',
    passwordPlaceholder: 'Password',
    loginButton: 'Login',
    successMessage: 'Login successful!',
    errorMessage: 'Invalid username or password',
    adminPanelTitle: 'Admin Panel',
    createUserTitle: 'Create user',
    fullNameLabel: 'Full name',
    emailLabel: 'Email',
    bankAccountLabel: 'Bank account number',
    bankCardLabel: 'Bank card number',
    documentUploadLabel: 'Document',
    documentUploadHint: 'Uploading is disabled for now',
    createButton: 'Create',
    searchUserTitle: 'Search user',
    searchPrompt: 'Enter the full name to search',
    searchPlaceholder: 'E.g. Ivanov Ivan Ivanovich',
    searchButton: 'Search',
    searchHint: 'The search looks for matches within the full name',
    userInfoTitle: 'User details',
    userNotSelected: 'No user selected',
    noMatchesFound: 'No users found',
    selectUserPrompt: 'Select a user from the list',
    noData: 'No data',
    logoutButton: 'Logout',
    userCreatedMessage: 'User created successfully',
    userFoundMessage: 'User found',
    bankAccountRequired: 'Bank account number is required',
    bankAccountInvalid: 'Bank account number must contain exactly 20 digits',
    bankCardRequired: 'Bank card number is required',
    bankCardInvalid: 'Bank card number must contain exactly 16 digits',
    myGrants: 'My Grants',
    remainingAmount: 'Remaining',
    noGrants: 'You have no grants',
    loadingGrants: 'Loading grants...',
    scanQRCode: 'Scan QR Code',
    scanningQR: 'Scanning...',
    qrScanSuccess: 'Operation approved',
    qrScanRejected: 'Operation rejected',
    uploadReceipt: 'Upload Receipt',
    receiptUploaded: 'Receipt uploaded successfully',
    receiptUploadError: 'Failed to upload receipt',
    confirmOperation: 'Confirm operation - upload receipt',
    statusNotPurchased: 'Not purchased',
    statusProcessing: 'Processing',
    statusCompleted: 'Completed',
    statusContractError: 'Contact support',
    statusContractErrorAdmin: 'Contact client',
    items: 'Items',
    noItems: 'No items',
    quantity: 'Quantity',
    productName: 'Product name',
    selectGrant: 'Select a grant',
    selectCategory: 'Select a category',
    passwordLabel: 'Password',
    passwordRequired: 'Password is required',
    downloadReceipt: 'Download Receipt',
    contactClient: 'Contact client',
  },
} as const;

export type Language = keyof typeof vocabulary;
export type TranslationKey = keyof (typeof vocabulary)['ru'];

